/**
 * QQNT 小黄脸表情。
 * 索引来自 koishi.js.org/QFace 的 assets/qq_emoji/_index.json（对齐 QQNT 官方表情包），
 * 静态 PNG 缩到 64px 落到 public/assets/qqface/：走同域，导出截图时不会跨域拿不到图。
 * 文件名就是这里的 file 字段；unicode 那类 id 换成 u{码点} 以免 URL 里带奇怪字符。
 */
export interface QFace {
  /** 文件名，同时当唯一 key */
  file: string;
  /** 正文里写 /名字 就会渲染成这张图 */
  name: string;
  /** 搜索用的别名 */
  words: string[];
}

export const qfaceUrl = (file: string) => `/assets/qqface/${file}.png`;

export const QFACES: QFace[] = [
  { file: '0', name: '惊讶', words: [] },
  { file: '1', name: '撇嘴', words: [] },
  { file: '2', name: '色', words: [] },
  { file: '3', name: '发呆', words: [] },
  { file: '4', name: '得意', words: [] },
  { file: '5', name: '流泪', words: [] },
  { file: '6', name: '害羞', words: [] },
  { file: '7', name: '闭嘴', words: [] },
  { file: '8', name: '睡', words: [] },
  { file: '9', name: '大哭', words: [] },
  { file: '10', name: '尴尬', words: [] },
  { file: '11', name: '发怒', words: [] },
  { file: '12', name: '调皮', words: [] },
  { file: '13', name: '呲牙', words: [] },
  { file: '14', name: '微笑', words: [] },
  { file: '15', name: '难过', words: [] },
  { file: '16', name: '酷', words: [] },
  { file: '19', name: '吐', words: [] },
  { file: '20', name: '偷笑', words: [] },
  { file: '21', name: '可爱', words: [] },
  { file: '22', name: '白眼', words: [] },
  { file: '23', name: '傲慢', words: [] },
  { file: '24', name: '饥饿', words: [] },
  { file: '25', name: '困', words: [] },
  { file: '26', name: '惊恐', words: [] },
  { file: '27', name: '流汗', words: [] },
  { file: '28', name: '憨笑', words: [] },
  { file: '29', name: '悠闲', words: [] },
  { file: '30', name: '奋斗', words: [] },
  { file: '31', name: '咒骂', words: [] },
  { file: '32', name: '疑问', words: [] },
  { file: '33', name: '嘘', words: [] },
  { file: '34', name: '晕', words: [] },
  { file: '35', name: '折磨', words: [] },
  { file: '36', name: '衰', words: [] },
  { file: '37', name: '骷髅', words: [] },
  { file: '38', name: '敲打', words: [] },
  { file: '39', name: '再见', words: [] },
  { file: '41', name: '发抖', words: [] },
  { file: '43', name: '跳跳', words: [] },
  { file: '46', name: '猪头', words: [] },
  { file: '49', name: '拥抱', words: [] },
  { file: '59', name: '便便', words: [] },
  { file: '64', name: '凋谢', words: [] },
  { file: '75', name: '月亮', words: [] },
  { file: '78', name: '握手', words: [] },
  { file: '86', name: '怄火', words: [] },
  { file: '89', name: '西瓜', words: [] },
  { file: '98', name: '抠鼻', words: [] },
  { file: '99', name: '鼓掌', words: [] },
  { file: '101', name: '坏笑', words: [] },
  { file: '102', name: '左哼哼', words: [] },
  { file: '109', name: '左亲亲', words: [] },
  { file: '110', name: '吓', words: [] },
  { file: '111', name: '可怜', words: [] },
  { file: '112', name: '菜刀', words: [] },
  { file: '114', name: '篮球', words: [] },
  { file: '116', name: '示爱', words: [] },
  { file: '124', name: 'OK', words: [] },
  { file: '125', name: '转圈', words: [] },
  { file: '144', name: '喝彩', words: [] },
  { file: '174', name: '无奈', words: [] },
  { file: '175', name: '卖萌', words: [] },
  { file: '176', name: '小纠结', words: [] },
  { file: '177', name: '喷血', words: [] },
  { file: '178', name: '斜眼笑', words: [] },
  { file: '179', name: 'doge', words: [] },
  { file: '181', name: '戳一戳', words: [] },
  { file: '182', name: '笑哭', words: [] },
  { file: '183', name: '我最美', words: [] },
  { file: '185', name: '羊驼', words: [] },
  { file: '187', name: '幽灵', words: [] },
  { file: '201', name: '点赞', words: [] },
  { file: '212', name: '托腮', words: [] },
  { file: '262', name: '脑阔疼', words: [] },
  { file: '263', name: '沧桑', words: [] },
  { file: '264', name: '捂脸', words: [] },
  { file: '265', name: '辣眼睛', words: [] },
  { file: '267', name: '头秃', words: [] },
  { file: '269', name: '暗中观察', words: [] },
  { file: '271', name: '吃瓜', words: [] },
  { file: '272', name: '呵呵哒', words: [] },
  { file: '273', name: '我酸了', words: [] },
  { file: '277', name: '汪汪', words: [] },
  { file: '282', name: '敬礼', words: [] },
  { file: '283', name: '狂笑', words: [] },
  { file: '284', name: '面无表情', words: [] },
  { file: '289', name: '睁眼', words: [] },
  { file: '297', name: '拜谢', words: [] },
  { file: '298', name: '元宝', words: [] },
  { file: '299', name: '牛啊', words: [] },
  { file: '300', name: '胖三斤', words: [] },
  { file: '302', name: '左拜年', words: [] },
  { file: '303', name: '右拜年', words: [] },
  { file: '305', name: '右亲亲', words: [] },
  { file: '306', name: '牛气冲天', words: [] },
  { file: '307', name: '喵喵', words: [] },
  { file: '311', name: '打call', words: [] },
  { file: '312', name: '变形', words: [] },
  { file: '314', name: '仔细分析', words: [] },
  { file: '317', name: '菜汪', words: [] },
  { file: '318', name: '崇拜', words: [] },
  { file: '319', name: '比心', words: [] },
  { file: '320', name: '庆祝', words: [] },
  { file: '323', name: '嫌弃', words: [] },
  { file: '324', name: '吃糖', words: [] },
  { file: '325', name: '惊吓', words: [] },
  { file: '326', name: '生气', words: [] },
  { file: '332', name: '举牌牌', words: [] },
  { file: '333', name: '烟花', words: [] },
  { file: '334', name: '虎虎生威', words: [] },
  { file: '336', name: '豹富', words: [] },
  { file: '337', name: '花朵脸', words: [] },
  { file: '338', name: '我想开了', words: [] },
  { file: '339', name: '舔屏', words: [] },
  { file: '341', name: '打招呼', words: [] },
  { file: '342', name: '酸Q', words: [] },
  { file: '343', name: '我方了', words: [] },
  { file: '344', name: '大怨种', words: [] },
  { file: '345', name: '红包多多', words: [] },
  { file: '346', name: '你真棒棒', words: [] },
  { file: '347', name: '大展宏兔', words: [] },
  { file: '349', name: '坚强', words: [] },
  { file: '350', name: '贴贴', words: [] },
  { file: '351', name: '敲敲', words: [] },
  { file: '352', name: '咦', words: [] },
  { file: '353', name: '拜托', words: [] },
  { file: '354', name: '尊嘟假嘟', words: [] },
  { file: '355', name: '耶', words: [] },
  { file: '356', name: '666', words: [] },
  { file: '357', name: '裂开', words: [] },
  { file: '392', name: '龙年快乐', words: ['龙年', '龙年平安', '龙年大吉'] },
  { file: '395', name: '略略略', words: [] },
  { file: '415', name: '划龙舟', words: ['端午', '端午快乐', '端午安康'] },
  { file: '419', name: '火车', words: ['国庆', '国庆快乐'] },
  { file: '424', name: '续标识', words: [] },
  { file: '425', name: '求放过', words: [] },
  { file: '426', name: '玩火', words: [] },
  { file: '427', name: '偷感', words: [] },
  { file: '428', name: '收到', words: [] },
  { file: '429', name: '蛇年快乐', words: ['蛇年', '蛇年平安', '蛇年大吉'] },
  { file: 'u2600', name: '晴天', words: [] },
  { file: 'u2615', name: '咖啡', words: [] },
  { file: 'u2728', name: '闪光', words: [] },
  { file: 'u2754', name: '问号', words: [] },
  { file: 'u1f339', name: '玫瑰', words: [] },
  { file: 'u1f34e', name: '苹果', words: [] },
  { file: 'u1f353', name: '草莓', words: [] },
  { file: 'u1f35c', name: '拉面', words: [] },
  { file: 'u1f35e', name: '面包', words: [] },
  { file: 'u1f367', name: '刨冰', words: [] },
  { file: 'u1f37a', name: '啤酒', words: [] },
  { file: 'u1f37b', name: '干杯', words: [] },
  { file: 'u1f3ea', name: '便利店', words: [] },
  { file: 'u1f40e', name: '骑马', words: [] },
  { file: 'u1f414', name: '公鸡', words: [] },
  { file: 'u1f41b', name: '虫', words: [] },
  { file: 'u1f42e', name: '牛', words: [] },
  { file: 'u1f433', name: '鲸鱼', words: [] },
  { file: 'u1f435', name: '猴', words: [] },
  { file: 'u1f436', name: '狗', words: [] },
  { file: 'u1f437', name: '猪', words: [] },
  { file: 'u1f438', name: '青蛙', words: [] },
  { file: 'u1f440', name: '眼睛', words: [] },
  { file: 'u1f446', name: '向上', words: [] },
  { file: 'u1f44a', name: '拳头', words: [] },
  { file: 'u1f44c', name: '好的', words: [] },
  { file: 'u1f44d', name: '厉害', words: [] },
  { file: 'u1f44e', name: '鄙视', words: [] },
  { file: 'u1f462', name: '靴子', words: [] },
  { file: 'u1f466', name: '男孩', words: [] },
  { file: 'u1f467', name: '女孩', words: [] },
  { file: 'u1f489', name: '打针', words: [] },
  { file: 'u1f493', name: '爱心', words: [] },
  { file: 'u1f49d', name: '礼物', words: [] },
  { file: 'u1f4a3', name: '炸弹', words: [] },
  { file: 'u1f4a4', name: '睡觉', words: [] },
  { file: 'u1f4a6', name: '水', words: [] },
  { file: 'u1f4a8', name: '吹气', words: [] },
  { file: 'u1f4aa', name: '肌肉', words: [] },
  { file: 'u1f4eb', name: '邮箱', words: [] },
  { file: 'u1f525', name: '火', words: [] },
  { file: 'u1f52b', name: '手枪', words: [] },
  { file: 'u1f602', name: '激动', words: [] },
  { file: 'u1f604', name: '高兴', words: [] },
  { file: 'u1f60a', name: '嘿嘿', words: [] },
  { file: 'u1f60c', name: '羞涩', words: [] },
  { file: 'u1f60d', name: '花痴', words: [] },
  { file: 'u1f60f', name: '哼哼', words: [] },
  { file: 'u1f612', name: '不屑', words: [] },
  { file: 'u1f613', name: '汗', words: [] },
  { file: 'u1f614', name: '失落', words: [] },
  { file: 'u1f618', name: '飞吻', words: [] },
  { file: 'u1f61a', name: '亲亲', words: [] },
  { file: 'u1f61c', name: '淘气', words: [] },
  { file: 'u1f61d', name: '吐舌', words: [] },
  { file: 'u1f630', name: '紧张', words: [] },
  { file: 'u1f631', name: '害怕', words: [] },
  { file: 'u1f633', name: '瞪眼', words: [] },
  { file: 'u1f64f', name: '合十', words: [] },
  { file: 'u1f6ac', name: '吸烟', words: [] },
];

const BY_NAME = new Map(QFACES.map((f) => [f.name, f]));

export const qfaceByName = (name: string) => BY_NAME.get(name);

/** 名字按长度倒序，先匹配长的，免得 /大哭 被 /大 抢走 */
const NAMES = QFACES.map((f) => f.name)
  .filter(Boolean)
  .sort((a, b) => b.length - a.length);
const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
export const QFACE_RE = new RegExp(`/(${NAMES.map(esc).join('|')})`, 'g');
